### PR TITLE
feat(docker): redockerize application

### LINKED ISSUE #37: request: Better Dockerfile!
Just lack knowledge about docker. I think my dockerfile isn't efficient and bad for production.

### PR DESCRIPTION
**Pull request by Hazmi35**
Fixes #37

### CODE REVIEW

**Comment by Hazmi35** [comment]
Please note that I don't test this myself yet. but you can test it now if you want

**Comment by Hazmi35** [comment]
I have tested canvas on fortune-cookie, it is working, I don't really know canvas here so it is recommended to test this again

**Comment by Hazmi35** [comment]
Should we use docker volume on assets?

**Review by youKnowOwO — APPROVED** [review]
Thank you very much 🖌️. after I tested, the docker was 300MB smaller

**Pull request merged**
